import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import useGetValue from '../hooks/useGetValue'

const Home = () => {
  const posts = useGetValue('posts')
  
  const isLoading = posts.isLoading

   if (isLoading) {
    return <p>Fetching data...</p>
   }

   const dataPosts = Object.values(posts.snapshot)
   const dataPosts2 = Object.entries(posts.snapshot)
   //console.log(dataPosts2)

  return (
    
    
    <div className="container mx-auto mt-8">
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <div className="flex justify-between items-center pb-4 border-b border-dashed border-gray-900 mb-4">
      <h1 className="text-3xl font-semibold">Firebase Zaki 24</h1>
      <Link
        className="bg-green-600 hover:bg-opacity-80 text-white rounded-lg px-4 py-2 duration-200"
        href="/create"
      >
        Create New
      </Link>
      <Link
        className="bg-green-600 hover:bg-opacity-80 text-white rounded-lg px-4 py-2 duration-200"
        href="/remove"
      >
        Remove
      </Link>
    </div>

        { <div>
          {dataPosts2.map((item) => {
            return (
            
             <div key={item[0]} className="container mx-auto mt-8 border-b border-dashed border-gray-900" >
             <div className="flex items-center pb-4 mb-4">
             <strong> ID - </strong>{item[0]}
             </div> 
             <div className="flex items-center pb-4 mb-4">
             <strong> Title - </strong>{item[1].title}
             </div> 
             <div className="flex items-center pb-4 mb-4">
             <strong>Content - </strong>{item[1].content} 
             </div> 
             <div className="flex items-center pb-4 mb-4">
             <strong>Price - </strong>{item[1].price} 
             </div>
             <div className="flex items-center pb-4 mb-4">
             <strong>Timestamp - </strong>{item[1].timestamp} 
             </div>
                           
             <div className="flex item-right gap-2">
               <Link className="text-blue-700 underline hover:no-underline" href={`/${item[0]}/update`}>Update</Link>  
               <Link className="text-red-500 underline hover:no-underline" href={`/${item[0]}/edit`}>Edit</Link>              
             </div>
           </div> 
            )
          })}
        </div> }
  

    </div>
  )
}

export default Home
