import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import useUpdateValue from '../../hooks/useUpdateValue'
import { getDatabase, ref, child, get } from 'firebase/database'
import firebaseApp from '../../services/firebase-sdk'
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Home = () => {
  const router = useRouter();
  const { id } = router.query;

  const [task, setTask] = useState({
    content: "",
    price: "",
  });

  const onChange = (e) => {
    setTask({ ...task, [e.target.name]: e.target.value });
  };
  const updateAPost = useUpdateValue()
  const update = useUpdateValue()

  const updatePost = async () => {
    const path = '/posts'
    const value = {
      createdAt: new Date(),
      updatedAt: new Date(),
      categories: 'Life'
    }

    await updateAPost.updateDoc(path, value)
  }



  useEffect(() => {
    const fetchTask = async () => {
      const path= '/posts/' + id
      const database = getDatabase(firebaseApp)
      const rootReference = ref(database)
      const snapshot = await get(child(rootReference, path))
      const dbValue = snapshot.val()
      console.log(dbValue)     
      setTask({ id: dbValue.id, ...dbValue.data() });
    };

    if (id) {
      fetchTask();
    }
  }, [id]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto mt-8 max-w-[560px]">
        <div className="flex justify-between items-center pb-4 border-b border-dashed border-gray-900 mb-4">
          <h1 className="text-3xl font-semibold">Edit Task</h1>
        </div>
        <form>
          <div className="mb-4">
            <label>Title</label>
            <input
              className="mt-1 px-4 py-2 border border-gray-300 rounded-md block w-full"
              type="text"
              name="name"
              value={task?.content}
              onChange={onChange}
            />
          </div>
          <div className="mb-4">
            <label>Description</label>
            <input
              className="mt-1 px-4 py-2 border border-gray-300 rounded-md block w-full"
              type="text"
              name="description"
              value={task?.price}
              onChange={onChange}
            />
          </div>
          <button
            className="bg-green-600 hover:bg-opacity-80 text-white rounded-lg px-4 py-2 duration-200 w-full"
            type="button"
            onClick={updatePost}
          >
            Edit Task
          </button>
        </form>
      </div>

      {/* {isLoading && <h4>Fetching data...</h4>} */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={updatePost} style={{ background: 'red', padding: 8 }}>
          Update Doc
        </button>
        {/* <button
          onClick={updateCartAndProduct}
          style={{ background: 'blue', padding: 8 }}
        >
          Update Field
        </button> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
